// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDliJ4as4t4odNLtuXCp6FbBSOMhD8BfnI',
    appId: '1:135721863477:web:750248e7191ea07595a47c',
    messagingSenderId: '135721863477',
    projectId: 'alumni-app-4ece9',
    authDomain: 'alumni-app-4ece9.firebaseapp.com',
    storageBucket: 'alumni-app-4ece9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCzjbeFPnPWJcMkLJA1hwZI33izMBhZEU',
    appId: '1:135721863477:android:75ffbade6891381b95a47c',
    messagingSenderId: '135721863477',
    projectId: 'alumni-app-4ece9',
    storageBucket: 'alumni-app-4ece9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5Aq0N3FVmKm9J2U3cJPEw4GkTSevQ4M',
    appId: '1:135721863477:ios:bf33a2fe5813fada95a47c',
    messagingSenderId: '135721863477',
    projectId: 'alumni-app-4ece9',
    storageBucket: 'alumni-app-4ece9.firebasestorage.app',
    iosBundleId: 'com.example.alumniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI5Aq0N3FVmKm9J2U3cJPEw4GkTSevQ4M',
    appId: '1:135721863477:ios:bf33a2fe5813fada95a47c',
    messagingSenderId: '135721863477',
    projectId: 'alumni-app-4ece9',
    storageBucket: 'alumni-app-4ece9.firebasestorage.app',
    iosBundleId: 'com.example.alumniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDliJ4as4t4odNLtuXCp6FbBSOMhD8BfnI',
    appId: '1:135721863477:web:fe475dd73702f44295a47c',
    messagingSenderId: '135721863477',
    projectId: 'alumni-app-4ece9',
    authDomain: 'alumni-app-4ece9.firebaseapp.com',
    storageBucket: 'alumni-app-4ece9.firebasestorage.app',
  );

}